### ISSUE TITLE
libpam-slurm configuration method to be changed

### ISSUE THREAD

**Issue by Cec1le** [edf-hpc/slurm-llnl#2]
Remove "perm_denied=ignore" in slurm-llnl/debian/libpam-slurm.pam-auth-update.

End-users will not be able to access nodes that have the package installed unless they have a slurm job running on the node.

**Comment by mehdid** [comment]
Installation of the package should not prevent users from connecting to affected machines, withtout an explicit approval from the administrator. At least, the implemented mechanism should adopt an opt-in policy, and not the contrary.

**Comment by hmlth** [comment]
I think the package should provide pam-configs  file with ``required``, but with a ``default`` value to false. This way the package does not block authentication by default and the administrator can opt-in by selecting the pam profile in debconf.
